# permissions for end users to edit responseconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: responseconfig-editor-role
rules:
- apiGroups:
  - sporc.example.com
  resources:
  - responseconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sporc.example.com
  resources:
  - responseconfigs/status
  verbs:
  - get
