# permissions for end users to edit responses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: response-editor-role
rules:
- apiGroups:
  - sporc.example.com
  resources:
  - responses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sporc.example.com
  resources:
  - responses/status
  verbs:
  - get
