# permissions for end users to view responses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: response-viewer-role
rules:
- apiGroups:
  - sporc.example.com
  resources:
  - responses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sporc.example.com
  resources:
  - responses/status
  verbs:
  - get
